### ISSUE TITLE
Problem with the graphic representation for DMX lights

### ISSUE THREAD

**Issue by Eric6464** [calaos/calaos_mobile#10]
the color control bars are above the on / off control DMX lights.
This makes difficult to use the lights.

![screenshot_2015-10-14-21-41-02](https://cloud.githubusercontent.com/assets/9049130/10497923/ed2d4c6c-72c8-11e5-8c3f-379fc6d05b05.png)

**Comment by raoulh** [comment]
fixed in 90bf4c8eb899d8d706d3ac66c9a8f70dc2691686
