### ISSUE TITLE
Display problem with RGB Lights on Android

### ISSUE THREAD

**Issue by fredsch** [calaos/calaos_mobile#3]
![screenshot_2015-03-09-09-25-49](https://cloud.githubusercontent.com/assets/9051112/6551957/830e62ec-c640-11e4-8ec7-908d5774640e.png)
The color-strips are overlapping the power ON/OFF buttons, so it's very difficult to press these buttons.
This problem appairs only on Android Smartphones (Samsung S4), unfortunately I don't have an other device for testing. On IOS it's Ok !

**Comment by raoulh** [comment]
fixed
