### ISSUE TITLE
Favorites lost some times

### ISSUE THREAD

**Issue by BozTlse** [calaos/calaos_mobile#5]
Using Calaos_Mobile app with iPhone mobile.
The Favorites list is cleaned, now empty.

**Comment by tiramiseb** [comment]
Hello,

Same behaviour here, sometimes favorites are lost.
Android app on Samsung Galaxy Note 2.

I seem to have found a way to reproduce, but I'm not sure.
- wait for the login screen
- enter the credentials
- click on "login"
- be in a hurry and click on "login" again, while it is trying to connect

**Comment by BozTlse** [comment]
Hello,
I've just tried it as you say, and is erased the list.Good work !
thanks you,Arnaud. 

```
  De : Sébastien Maccagnoni-Munch <notifications@github.com>
```

 À : calaos/calaos_mobile calaos_mobile@noreply.github.com 
Cc : BozTlse aconrad2@yahoo.fr 
 Envoyé le : Jeudi 9 avril 2015 13h57
 Objet : Re: [calaos_mobile] Favorites lost some times (#5)

Hello,Same behaviour here, sometimes favorites are lost.
Android app on Samsung Galaxy Note 2.I seem to have found a way to reproduce, but I'm not sure.   
- wait for the login screen
- enter the credentials
- click on "login"
- be in a hurry and click on "login" again, while it is trying to connect
